### ISSUE TITLE
Specifying a repository

### ISSUE THREAD

**Issue by rgardler** [namshi/roger#23]
Is there a way to specify a repository within a registry? That is, if I want to publish a container adtd/web on DockerHub how can I specify the repository adtd?

**Comment by rgardler** [comment]
A little more experimenting showed that the following will work. As Roger assumes docker hub if no other registry is provided. The question remains how one would specify a repository if using an alternative registry. However, that's not my issue right now so I'm closing this one for now.

web:
  dockerfilePath: web
  registry: adtd

**Comment by odino** [comment]
hey @rgardler, thanks for asking!

I think this would do it:

``` yaml
web:
  registry: 127.0.0.1/repo
```

though I havent tested it!

**Comment by rgardler** [comment]
Nope, the '/' is not allowed (don't have the error message to hand but it looked like there is an RE validation of the value of `registry`).
