### ISSUE TITLE
Building Desktop Application

### ISSUE THREAD

**Issue by mikkeljohnsen** [namshi/roger#50]
Is it possible to use Roger to build Desktop Applications ?

I have a Docker image that contains my entire build environment and is able to compile and create installer (using NSIS/MSI and Mingw). How do I schedule a build that is running inside a Docker image but is not creating a Docker image itself ?

**Comment by odino** [comment]
Hey @mikkeljohnsen I think at the moment you wont be able to! This tool was made to be able to create docker images and push artifacts to repositories (S3, dockerhub, etc). You could theoretically push your build outputs to S3, but I'd say for this use case roger is a bit overkill :)

**Comment by mikkeljohnsen** [comment]
Thanks, any suggestions for a CI that can do that ?
